name: Build Atmosphere

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/d3fau4/nx-dev
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true

    - name: Build app
      run: |
        make all
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: .
