name: Build Atmosphere

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/d3fau4/nx-dev
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true
          fetch-depth: 0

    - name: Debug Git Information
      run: |
        git status
        git symbolic-ref --short HEAD || echo "No branch info"
        git rev-parse --short HEAD || echo "No commit info"


    - name: Build app
      run: |
        make dist
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: .
